export const products = [
  {
    id: 'prd-101',
    name: 'Analytics Workspace',
    category: 'SaaS',
    owner: 'Maya Patel',
    status: 'Active',
    price: 149,
    stock: 42,
    revenue: 18420,
  },
  {
    id: 'prd-102',
    name: 'Roadmap Planner',
    category: 'Productivity',
    owner: 'Jon Bell',
    status: 'Active',
    price: 79,
    stock: 68,
    revenue: 12640,
  },
  {
    id: 'prd-103',
    name: 'Customer Signals',
    category: 'Insights',
    owner: 'Sara Kim',
    status: 'Review',
    price: 119,
    stock: 24,
    revenue: 8925,
  },
  {
    id: 'prd-104',
    name: 'Launch Checklist',
    category: 'Operations',
    owner: 'Nolan Reed',
    status: 'Draft',
    price: 39,
    stock: 110,
    revenue: 4210,
  },
  {
    id: 'prd-105',
    name: 'Feedback Inbox',
    category: 'Support',
    owner: 'Ava Morgan',
    status: 'Active',
    price: 59,
    stock: 87,
    revenue: 9720,
  },
]

export const productStatuses = ['All', 'Active', 'Review', 'Draft']
